version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mariadb
    ports: [3306]
    labels:
      com.symfony.server.service-prefix: 'DATABASE'
  
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
